Feat/dashboard
The-Bugger-Ducks/owl-partners-web pull request #13
Opened 2023-05-26 00:31 UTC by gioliveirass

Documentação: https://github.com/The-Bugger-Ducks/owl-partners-web/issues/4#issuecomment-1563663038

2023-05-29 13:28 UTC, drisabelles commented
@ThHenrique @MariaGabrielaReis

2023-05-30 10:52 UTC, MariaGabrielaReis commented on src/pages/Dashboard/index.tsx
> +    toast.success("Dashboard carregada com sucesso!");
Precisamos mesmo de um toast para avisar que a dashboard foi carregada? Pq se ela foi carregada com sucesso  o loading vai parar e os dados vão aparecer na tela, não? Pode ser legal deixar o toast só em caso de erro/avisos

2023-05-30 11:04 UTC, MariaGabrielaReis requested changes
Fiz alguns apontamentos, se não for interessante pode só ignorar, são só algumas sugestões de melhoria ✨

2023-05-30 11:04 UTC, MariaGabrielaReis commented on src/pages/Dashboard/index.tsx
Percebi que todas as funções foram criada usando o padrão de constante, sendo que o resto do projeto (como a tela de login e outros componentes) estão usando o padrão de função com a palavra reservada `function`. Acho que seria legal a gente manter o padrão nesse caso também, mudando as funções desse estilo: 

```ts
 const getDashboardData = async () => {
    setIsLoading(true);
    const data = await dashboardRequests.get();
    setIsLoading(false);
    if (data === "error") {
      dashboardErrorToast();
      return;
    }
    setDashboardData(data);
    dashboardSuccessToast();
  };
```

Para este estilo:

```ts
 async function getDashboardData() {
    setIsLoading(true);
    const data = await dashboardRequests.get();
    setIsLoading(false);
    if (data === "error") {
      dashboardErrorToast();
      return;
    }
    setDashboardData(data);
    dashboardSuccessToast();
  };
```

2023-05-30 11:04 UTC, MariaGabrielaReis commented on src/pages/Dashboard/index.tsx
> +                dashboardData
Sugestão, trocar if ternário para o uso do &&, tirando o "undefined" hardcoded:

Antes:

```ts
 dashboardData
   ? dashboardData.top10MostMembers.reduce(
      (prev: any, curr: any) => {
           return [
               ...prev,
               { name: curr.name, total: curr.memberNumber ?? 0  },
            ];
        },
      []
    )
   : undefined
```

Depois:

```ts
 dashboardData && dashboardData.top10MostMembers.reduce(
      (prev: any, curr: any) => {
           return [
               ...prev,
               { name: curr.name, total: curr.memberNumber ?? 0  },
            ];
        },
   []
 )
```

2023-05-30 11:04 UTC, MariaGabrielaReis commented on src/pages/Dashboard/index.tsx
> +                  ? dashboardData.partnersPerStatus.reduce(
Mesmo ponto de tirar o undefined hardcoded tirando o if ternário e colocando o operador &&:

```ts
 dashboardData && dashboardData.partnersPerStatus.reduce(
      (prev: any, curr: any) => {
           return [
               ...prev,
               { name: formatLabel(curr.status), total: curr._count }
            ];
        },
   []
 )
```

2023-05-30 11:04 UTC, MariaGabrielaReis commented on src/pages/Dashboard/index.tsx
> +                  ? dashboardData.partnersPerState.reduce(
Mesmo ponto de tirar o undefined hardcoded tirando o if ternário e colocando o operador &&:

```ts
 dashboardData && dashboardData.partnersPerState.reduce(
      (prev: any, curr: any) => {
           return [
               ...prev,
               { name: curr.state, total: curr._count }
            ];
        },
   []
 )
```

2023-05-30 11:04 UTC, MariaGabrielaReis commented on src/pages/Dashboard/index.tsx
> +                  ? dashboardData.partnerPerClassification.reduce(
Mesmo ponto de tirar o undefined hardcoded tirando o if ternário e colocando o operador &&:

```ts
 dashboardData && dashboardData.partnerPerClassification.reduce(
      (prev: any, curr: any) => {
           return [
               ...prev,
               { name: formatLabel(curr.classification),  total: curr._count }
            ];
        },
   []
 )
```

2023-05-30 12:12 UTC, gioliveirass commented on src/pages/Dashboard/index.tsx
> +    toast.success("Dashboard carregada com sucesso!");
@MariaGabrielaReis tem como recarregar a página

2023-05-30 21:44 UTC, gioliveirass commented on src/pages/Dashboard/index.tsx
ok

2023-06-01 14:23 UTC, MariaGabrielaReis approved these changes

2023-06-02 19:41 UTC, merged